const TypographyWeb = ({
    Special:{fontWeight: 700, fontSize: "64px", lineHeight: "84px", fontStyle: "normal",},
    Heading_1_regular:{fontWeight: 400, fontSize: "48px", lineHeight: "64px", fontStyle: "normal",},
    Heading_1_medium:{fontWeight: 500, fontSize: "48px", lineHeight: "64px", fontStyle: "normal",},
    Heading_1_bold:{fontWeight: 700, fontSize: "48px", lineHeight: "64px", fontStyle: "normal",},
    Heading_2_bold:{fontWeight: 700, fontSize: "40px", lineHeight: "54px", fontStyle: "normal",},
    Heading_3_medium:{fontWeight: 500, fontSize: "32px", lineHeight: "44px", fontStyle: "normal",},
    Heading_3_bold:{fontWeight: 700, fontSize: "32px", lineHeight: "44px", fontStyle: "normal",},
    SubHeading_regular:{fontWeight: 400, fontSize: "24px", lineHeight: "34px", fontStyle: "normal",},
    SubHeading_bold:{fontWeight: 700, fontSize: "24px", lineHeight: "34px"},
    SubHeading_bold_underLine:{fontWeight: 700, fontSize: "24px", lineHeight: "34px", fontStyle: "normal",textDecoration:"underline"},
    Body_regular:{fontWeight: 400, fontSize: "18px", lineHeight: "28px", fontStyle: "normal",},
    Body_bold:{fontWeight: 700, fontSize: "18px", lineHeight: "28px", fontStyle: "normal",},
    Caption_regular:{fontWeight: 400, fontSize: "16px", lineHeight: "26px", fontStyle: "normal",},
    Caption_underLine:{fontWeight: 400, fontSize: "16px", lineHeight: "26px", fontStyle: "normal",textDecoration:"underline"},
    Caption_italic:{fontWeight: 400, fontSize: "16px", lineHeight: "26px", fontStyle: "italic"},
    Caption_medium:{fontWeight: 500, fontSize: "16px", lineHeight: "26px", fontStyle: "normal"},
    Label_regular:{fontWeight: 400, fontSize: "14px", lineHeight: "24px", fontStyle: "normal",letterSpacing:"0.28px"},
    Label_italic:{fontWeight: 400, fontSize: "14px", lineHeight: "24px", fontStyle: "italic",letterSpacing:"0.28px"},
    Label_medium:{fontWeight: 500, fontSize: "14px", lineHeight: "24px", fontStyle: "italic",letterSpacing:"0.28px"},
    Label_bold:{fontWeight: 700, fontSize: "14px", lineHeight: "24px", fontStyle: "italic",letterSpacing:"0.28px"},
})

const TypographyMobile = ({
    // Heading_1_bold:{fontWeight: 700, fontSize: "40px", lineHeight: "54px", fontStyle: "normal",},
    Heading_2_regular:{fontWeight: 400, fontSize: "32px", lineHeight: "44px", fontStyle: "normal",},
    Heading_2_bold:{fontWeight: 700, fontSize: "32px", lineHeight: "44px", fontStyle: "normal",},
    Heading_3_bold:{fontWeight: 700, fontSize: "28px", lineHeight: "40px", fontStyle: "normal",},
    Heading_4_regular:{fontWeight: 400, fontSize: "24px", lineHeight: "34px", fontStyle: "normal",},
    Heading_4_medium:{fontWeight: 500, fontSize: "24px", lineHeight: "34px", fontStyle: "normal",},
    Heading_4_bold:{fontWeight: 700, fontSize: "24px", lineHeight: "34px", fontStyle: "normal",},
    SubHeading_regular:{fontWeight: 400, fontSize: "18px", lineHeight: "28px", fontStyle: "normal",},
    SubHeading_bold:{fontWeight: 700, fontSize: "18px", lineHeight: "28px"},
    Body_regular:{fontWeight: 400, fontSize: "16px", lineHeight: "26px", fontStyle: "normal",},
    Body_medium:{fontWeight: 500, fontSize: "16px", lineHeight: "26px", fontStyle: "normal",},
    Caption_regular:{fontWeight: 400, fontSize: "14px", lineHeight: "26px",letterSpacing:"0.28px", fontStyle: "normal",},
    Caption_underLine:{fontWeight: 400, fontSize: "14px", lineHeight: "26px",letterSpacing:"0.28px", fontStyle: "normal",textDecoration:"underline"},
    Caption_italic:{fontWeight: 400, fontSize: "14px", lineHeight: "26px",letterSpacing:"0.28px", fontStyle: "italic"},
    Caption_medium:{fontWeight: 500, fontSize: "14px", lineHeight: "26px",letterSpacing:"0.28px", fontStyle: "normal"},
    Label_bold:{fontWeight: 700, fontSize: "12px", lineHeight: "22px", fontStyle: "normal",letterSpacing:"0.6px"},
})
export default {...TypographyWeb,...TypographyMobile}
